arrowParens: avoid
bracketSpacing: true
endOfLine: auto
htmlWhitespaceSensitivity: css
jsxBracketSameLine: false
printWidth: 120
proseWrap: preserve
requirePragma: false
semi: true
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
vueIndentScriptAndStyle: true
